### ISSUE TITLE
Request for the whole data in Jacksonville and Omaha

### ISSUE THREAD

**Issue by lauraset** [pubgeo/monocular-geocentric-pose#6]
Hello, you did excellent work by releasing a large stereo data. I downloaded the U3SD dataset, but found that it didn't cover the whole city (see the worldview-3 images of Jacksonville in the following figure). Do you have plans to release the whole worldview-3 images and the corresponding Lidar point cloud?  I want to use the whole data covered the two cities, i.e., Jacksonville and Omaha, to do some research. Thank you in advance.
![image](https://user-images.githubusercontent.com/39206462/114178082-c9bda280-996f-11eb-9978-855b37c1bed7.png)

**Comment by pubgeo** [comment]
The full satellite images used to produce our data set is hosted here by our friends at SpaceNet: https://spacenet.ai/core3d/. There's also info there about how to find the source lidar data.

**Comment by lauraset** [comment]
thank you for your help.
