### ISSUE TITLE
Could you plz share your pretrain model for testing

### ISSUE THREAD

**Issue by jerrywyn** [pubgeo/monocular-geocentric-pose#7]
Could you plz share your pretrain model in  pytorch version for testing? I want to test the model first, which may help to quickly understand the effect of your method.

**Comment by pubgeo** [comment]
It's there under /releases, along with the older model's TF pretrained weights.

**Comment by jerrywyn** [comment]
这是来自QQ邮箱的假期自动回复邮件。
